/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamos;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author TOBIAS
 */
public class FrmNuevoPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form FrmNuevoPrestamo
     */
    Prestamos a = new Prestamos();
    ResultSet rstCarnets=null;
    DefaultComboBoxModel mdlCarnets = new DefaultComboBoxModel();
    ResultSet rstArticulos=null; 
    DefaultComboBoxModel mdlArticulos = new DefaultComboBoxModel();
    DefaultComboBoxModel mdlDia = new DefaultComboBoxModel();
   
    public FrmNuevoPrestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtCodigo.setEnabled(true);
         Actualizar();
         txtCodigo.setText(""+a.siguienteCod());
         txtCodigo.setEnabled(false);
    }
    private void Actualizar(){
        mdlArticulos.removeAllElements();
        mdlCarnets.removeAllElements();
        mdlDia.removeAllElements();
        mdlDia.addElement("DIAS");
         cmbDia.setModel(mdlDia);
         cmbDia.setEnabled(false);
        rstCarnets= a.Carnets();
        rstArticulos = a.Articulos();
        mdlCarnets.addElement("Seleccionar");
         try {
            while (rstCarnets.next()){
                
                mdlCarnets.addElement(rstCarnets.getString(1));
            }
            cmbCarnet.setModel(mdlCarnets);
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmNuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         mdlArticulos.addElement("Seleccionar");
         try {
            while (rstArticulos.next()){
                
                mdlArticulos.addElement(rstArticulos.getString(2));
            }
            cmbArticulo.setModel(mdlArticulos);
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmNuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private boolean Bisiesto(int a){
        
            boolean bisiesto=false;
            if(a%4==0){
                
            if(a%100==0 ){
                if(a%400==0){
                    bisiesto=true;
                }
                else{
                    bisiesto=false;               }
            }
            else{
            bisiesto=true;    
            }
            }
            
            return bisiesto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCarnet = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbArticulo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cmbAnio = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(cmbCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 64, -1, -1));

        jButton1.setText("Agregar alumno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 63, -1, -1));

        jLabel1.setText("Elija el carnet:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 67, -1, -1));

        getContentPane().add(cmbArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 125, -1, -1));

        jLabel2.setText("Elija el articulo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 128, -1, -1));

        jButton2.setText("Nuevo articulo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 124, -1, -1));

        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 176, -1, -1));

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 173, 47, -1));

        jLabel4.setText("Fecha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 217, -1, -1));

        jButton3.setText("Realizar prestamo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 259, -1, -1));

        cmbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AÑO", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2026", "2027", "2028", "2029", "2030" }));
        cmbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnioActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 214, -1, -1));

        cmbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MES", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 214, -1, -1));

        jLabel6.setText("Codigo del prestamo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 86, -1));

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 259, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REGISTRARSE.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(cmbAnio.getSelectedIndex()==0||cmbArticulo.getSelectedIndex()==0||cmbCarnet.getSelectedIndex()==0||cmbDia.getSelectedIndex()==0||cmbMes.getSelectedIndex()==0||txtCantidad.getText().length()==0){
          JOptionPane.showMessageDialog(null,"Debe llenar todos los campos");  
        }
        else{
            int cod=Integer.parseInt(txtCodigo.getText());
        int cantidad=Integer.parseInt(txtCantidad.getText());
        int idArticulo=cmbArticulo.getSelectedIndex();
        String carnet= ""+cmbCarnet.getSelectedItem();
        String fecha = cmbAnio.getSelectedItem()+"/"+cmbMes.getSelectedIndex()+"/"+cmbDia.getSelectedItem();
        a.insertarPrestamo(cod,carnet ,idArticulo ,cantidad, fecha);
        JOptionPane.showMessageDialog(null,"Prestamo exitoso");
        FrmPrincipal obj=new FrmPrincipal();
        obj.setVisible(true);
        this.dispose();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmAgregarAlumno obj = new FrmAgregarAlumno();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        // TODO add your handling code here:
        int i = cmbMes.getSelectedIndex();
        mdlDia.removeAllElements();
        mdlDia.addElement("DIAS");
        if(i==0){
            cmbDia.setEnabled(false);
        }
        else{
            cmbDia.setEnabled(true);
        }
        
        if(i==1||i==3||i==5||i==7||i==8||i==10||i==12){
           
           for(int j=1;j<=31;j++){
               mdlDia.addElement(""+j);
           }
            
        }
        else if(i==2){
            if(cmbAnio.getSelectedIndex()==0){
              for(int j=1;j<=28;j++){
               mdlDia.addElement(""+j);
              }
            }
            else{
                int a= Integer.parseInt((String) cmbAnio.getSelectedItem());
                
            if(Bisiesto(a)==true){
             for(int j=1;j<=29;j++){
               mdlDia.addElement(""+j);
           }    
            }else{
             for(int j=1;j<=28;j++){
               mdlDia.addElement(""+j);
           }   
            }    
            }
            
            
             
        }
        else{
             for(int j=1;j<=30;j++){
               mdlDia.addElement(""+j);
           }
        }
        cmbDia.setModel(mdlDia);
        
    }//GEN-LAST:event_cmbMesActionPerformed

    private void cmbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnioActionPerformed
        // TODO add your handling code here:
        
         if(cmbAnio.getSelectedIndex()!=0){
             int a= Integer.parseInt((String) cmbAnio.getSelectedItem());
        if(cmbMes.getSelectedIndex()==2 && Bisiesto(a)==true){
            mdlDia.removeAllElements();
        mdlDia.addElement("DIAS");
            for(int j=1;j<=29;j++){
               mdlDia.addElement(""+j);
           }  
        }
        else{
            mdlDia.removeAllElements();
        mdlDia.addElement("DIAS");
            for(int j=1;j<=28;j++){
               mdlDia.addElement(""+j);
           }  
        }
        cmbDia.setModel(mdlDia);     
         }       
        
    }//GEN-LAST:event_cmbAnioActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        char tecla= evt.getKeyChar();
        if(Character.isDigit(tecla)){
            if(txtCantidad.getText().length()>1){
                evt.consume();
            }
            
        }
        else{
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int id=cmbArticulo.getItemCount();
        String t=JOptionPane.showInputDialog("Ingrese el nombre del articulo");
        a.agregarArticulo(id,t );
        Actualizar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDiaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FrmPrincipal obj=new FrmPrincipal();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNuevoPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAnio;
    private javax.swing.JComboBox<String> cmbArticulo;
    private javax.swing.JComboBox<String> cmbCarnet;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
